import numpy as np
import pytest
import onnx
import onnx.numpy_helper

from onnx_to_gurobi.operators.averagepool import AveragePoolOperator
from onnx_to_gurobi.operators.matmul import MatMul
from onnx_to_gurobi.operators.operator_factory import OperatorFactory

"""
    Helper functions for building up operator factory unit tests
"""
def transform_names_to_dict(name_list):
    return [
        {"name": name, "shape": [None]}
        for name in name_list
    ]

def convert_onnx_attributes_to_dict(attribute_list):
    attributes_dict = {}

    for attr in attribute_list:
        if attr.type == onnx.AttributeProto.INT:
            attributes_dict[attr.name] = attr.i
        elif attr.type == onnx.AttributeProto.INTS:
            attributes_dict[attr.name] = list(attr.ints)
        elif attr.type == onnx.AttributeProto.FLOAT:
            attributes_dict[attr.name] = attr.f
        elif attr.type == onnx.AttributeProto.FLOATS:
            attributes_dict[attr.name] = list(attr.floats)

    return attributes_dict

"""
    Test cases for the operator factory. It's handling for nodes with different optypes are testes by handling 
    the corresponding modules, generated by the onnx-generator while unit-tests.
"""

@pytest.mark.operatorfactory_avgpool
def test_op_factory_avgpool():
    # Uniersal operator factory
    factory = OperatorFactory()

    # Testing operator factory for avgpool module
    model = onnx.load('tests/models/tens_avgpool.onnx')
    graph = model.graph
    nodes = graph.node
    initializers = graph.initializer
    if len(nodes) != 1:
        raise ValueError(f"Unit-ONNX Module should only have one node. But {len(nodes)} where found.")
    nodes_dict = {
        "name": nodes[0].name,
        "type": nodes[0].op_type,
        'input': transform_names_to_dict(nodes[0].input),
        'output': transform_names_to_dict(nodes[0].output),
        'attributes': convert_onnx_attributes_to_dict(nodes[0].attribute),
        'initializers': initializers,
        'constants': initializers
    }
    initializers_dict = {}
    for initializer in initializers:
        name = initializer.name
        tensor_array = onnx.numpy_helper.to_array(initializer)
        initializers_dict[name] = tensor_array

    avg_operator = factory.create_operator(nodes_dict, initializers_dict)
    assert isinstance(avg_operator, AveragePoolOperator), \
        f"Expected operator-type should be AvgPoolOperator, not {type(avg_operator)}."

    kernel_shape_attr = next(
        (attr for attr in nodes[0].attribute if attr.name == 'kernel_shape'),
        None
    )
    assert avg_operator.kernel_shape == list(kernel_shape_attr.ints), \
        f"Expected kernel shapes dont match: {avg_operator.kernel_shape}."

    stride_attr = next(
        (attr for attr in nodes[0].attribute if attr.name == 'strides'),
        None
    )
    assert avg_operator.strides == list(stride_attr.ints), \
        f"Expected strides dont match: {avg_operator.strides}."


@pytest.mark.operatorfactory_matmul
def test_op_factory_matmul():
    # Universal operator factory
    factory = OperatorFactory()

    # Testing operator factory for matmul module
    model = onnx.load('tests/models/tens_matmul.onnx')
    graph = model.graph
    nodes = graph.node
    initializers = graph.initializer
    if len(nodes) != 1:
        raise ValueError(f"Unit-ONNX Module should only have one node. But {len(nodes)} where found.")
    nodes_dict = {
        "name": nodes[0].name,
        "type": nodes[0].op_type,
        'input': transform_names_to_dict(nodes[0].input),
        'output': transform_names_to_dict(nodes[0].output),
        'attributes': convert_onnx_attributes_to_dict(nodes[0].attribute),
        'initializers': initializers,
        'constants': initializers
    }
    initializers_dict = {}
    for initializer in initializers:
        name = initializer.name
        tensor_array = onnx.numpy_helper.to_array(initializer)
        initializers_dict[name] = tensor_array

    matmul_operator = factory.create_operator(nodes_dict, initializers_dict)

    assert isinstance(matmul_operator, MatMul), \
        f"Expected operator-type should be AvgPoolOperator, not {type(matmul_operator)}."